version: '3'
services:
  intuitiv-identity-server:
    build: .
    ports:
      - 9000:9000
    command: ["node", "./src/server.js"]
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:27017"
      port: 9000,
      NODE_ENV: "qa"
    depends_on:
      - mongodb
      - redis

  mongoexport:
    build: ./mongo-shell
    environment:
      MongoDB: "mongodb://mongodb:27017"
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:4.1
    ports:
      - 27017:27017

  redis:
    image: redis