version: '3'
services:

  mongodb:
    image: mongo:4.1
    ports:
      - 27017:27017
    healthcheck:
        test: ["CMD", "bash", "/mongo-healthcheck"]
        interval: 1m
        timeout: 10s
        retries: 3

  redis:
    image: redis

  identity-server:
    build: .
    ports:
      - 3000:3000
    # command: ["node", "./src/server.js"]
    environment:
      MONGO_CONNECTION_STRING: "mongodb://mongodb:27017/intuitiv"
      PORT: 3000
      NODE_ENV: "dev"
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  mongoexport:
    build: ./mongo-shell
    environment:
      MongoDB: "mongodb://mongodb:27017"
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb